server:
  env: development
  port: 3000
  host: localhost:3000/
  scheme: https
  app: PROJECTONE
  version: 1.0.0

db:
  dbname: api-echo-project1
  dbuser: postgres
  dbpass: 213123asd
  dbport: 5432
  dbhost: localhost
  dbsslmode: disable
  dbtz: asia/Jakarta

logging:
  gormlevel: 4
  logruslevel: 4
